"""add unique constraint on recent views

Revision ID: a801eed04fc0
Revises: 3fad8e15fa02
Create Date: 2026-07-02 16:12:51.552750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a801eed04fc0'
down_revision = '3fad8e15fa02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recent_views', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_user_city_country', ['user_id', 'city', 'country'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recent_views', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_city_country', type_='unique')

    # ### end Alembic commands ###
